"""baseline

Revision ID: f141f2cca46f
Revises: 
Create Date: 2026-09-04 12:27:07.205755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f141f2cca46f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_league_id', sa.String(length=64), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('roster_positions', sa.JSON(), nullable=False),
    sa.Column('scoring_settings', sa.JSON(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('playoff_teams', sa.Integer(), nullable=False),
    sa.Column('playoff_week_start', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_season_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_player_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('snap_share', sa.Float(), nullable=True),
    sa.Column('red_zone_opportunities', sa.Integer(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_player_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gsis_id', sa.String(length=16), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('injury_status', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'platform_player_id')
    )
    op.create_table('position_volatility_priors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('low_ratio', sa.Float(), nullable=False),
    sa.Column('high_ratio', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_defense_strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('points_allowed_avg', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('opponent', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('platform_matchup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('platform_player_id', sa.String(length=32), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('expected_opportunities', sa.Float(), nullable=True),
    sa.Column('prior_season_weight', sa.Float(), nullable=True),
    sa.Column('dominant_category', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('platform_roster_id', sa.String(length=64), nullable=False),
    sa.Column('platform_owner_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('points_for', sa.Float(), nullable=False),
    sa.Column('points_against', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('my_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['my_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_hash')
    )
    op.create_table('roster_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('platform_player_id', sa.String(length=32), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['matchup_id'], ['matchups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_scores')
    op.drop_table('roster_slots')
    op.drop_table('league_connections')
    op.drop_table('teams')
    op.drop_table('projection_records')
    op.drop_table('matchups')
    op.drop_table('team_matchups')
    op.drop_table('team_defense_strength')
    op.drop_table('position_volatility_priors')
    op.drop_table('players')
    op.drop_table('player_usage_stats')
    op.drop_table('player_season_baselines')
    op.drop_table('leagues')
    # ### end Alembic commands ###
